### PR TITLE
Rephrase

### PR DESCRIPTION
**Pull request by vanillajonathan**
As per https://en.wikipedia.org/wiki/Wake-on-LAN

### CODE REVIEW

**Comment by swsnr** [comment]
If this is important, let's please use Wake On LAN, ie no dashes 🙂

**Review by swsnr — CHANGES_REQUESTED** [review]
If this is important, let's please use Wake On LAN, ie no dashes 🙂

**Comment by vanillajonathan** [comment]
Wikipedia names it Wake-on-LAN with dashes so I assume that is the proper way to write it.

**Comment by swsnr** [comment]
I don't think there's a "proper way to write it".  Microsoft calls it "Wake On LAN" (e.g. [here](https://learn.microsoft.com/en-us/surface/wake-on-lan-for-surface-devices)), and Wireshark writes [WriteOnLAN](https://wiki.wireshark.org/WakeOnLAN) :slightly_smiling_face: 

The official name would be "Magic Packet" technology, at least, that's the name used in the original whitepaper from like 1995 or so, which doesn't even mention "wake on LAN" in any particular spelling :wink: 

And as I find dashes in names ugly, I'd say "Wake On LAN" presents a reasonable compromise :wink:  Would you mind to update this PR accordingly?

**Comment by vanillajonathan** [comment]
Okay.

**Review by swsnr — APPROVED** [review]

**Pull request closed without merging**
